name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    # build at least daily at UTC 00:00 to keep the Z3 build cache warm
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Tree
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Check Copyright Headers
      run: checks/headers
    - name: Create Z3 Build Directory
      run: mkdir z3/build
    - name: Cache Z3 Build
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/vampire/z3/build
        key: ${{runner.os}}-z3-v1-${{hashFiles('.git/modules/z3/HEAD')}}
    - name: Configure Z3 Build
      working-directory: ${{runner.workspace}}/vampire/z3/build
      run: test -f libz3.so || cmake .. -DCMAKE_BUILD_TYPE=Debug
      env:
        CXX: clang++
    - name: Z3 Build
      working-directory: ${{runner.workspace}}/vampire/z3/build
      run: test -f libz3.so || make -j8
    - name: Create Build Directory
      run: mkdir build
    - name: Configure Build
      working-directory: ${{runner.workspace}}/vampire/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
      env:
        CXX: clang++
    - name: Build
      working-directory: ${{runner.workspace}}/vampire/build
      run: make -j8
    - name: Run Unit Tests
      working-directory: ${{runner.workspace}}/vampire/build
      run: ctest --output-on-failure
    - name: Find Vampire Binary
      run: cp build/bin/vampire_* vampire
    - name: Run Sanity Checks
      run: checks/sanity vampire
