name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Directory
      run: mkdir ${{runner.workspace}}/vampire/build
    - name: Configure Build
      working-directory: ${{runner.workspace}}/vampire/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
      env:
        CXX: clang++
    - name: Build
      working-directory: ${{runner.workspace}}/vampire/build
      run: make -j8
    - name: Install clang-tidy
      run: sudo apt install clang-tidy
    - name: Run clang-tidy
      working-directory: ${{runner.workspace}}/vampire/build
      run: run-clang-tidy -header-filter='.*' -j8
